Improve the test code.

diff --git a/.github/workflows/ci_03_enum_isodelaunay.yml b/.github/workflows/ci_03_enum_isodelaunay.yml
--- a/.github/workflows/ci_03_enum_isodelaunay.yml
+++ b/.github/workflows/ci_03_enum_isodelaunay.yml
@@ -113,4 +113,8 @@ jobs:
 
           cd CI_tests/Tspaces_IsoDelaunay
           ../../gap.sh < TestEnumIsoDelaunayDomain.g
+          if [ ! -f "CI_CONCLUSION" ]; then
+            echo "Error: file not found!" >&2
+            exit 1
+          fi
           cd ../..
diff --git a/.github/workflows/ci_07_facelatticegen.yml b/.github/workflows/ci_07_facelatticegen.yml
--- a/.github/workflows/ci_07_facelatticegen.yml
+++ b/.github/workflows/ci_07_facelatticegen.yml
@@ -108,4 +108,9 @@ jobs:
           # Running the test
           cd CI_tests/GroupSkeleton
           ../../gap.sh < TestGroupSkeleton.g
+          if [ ! -f "CI_CONCLUSION" ]; then
+            echo "Error: file not found!" >&2
+            exit 1
+          fi
           cd ../..
+          echo "After all the test face lattice code"
diff --git a/.github/workflows/ci_11_equistabdatabase.yml b/.github/workflows/ci_11_equistabdatabase.yml
--- a/.github/workflows/ci_11_equistabdatabase.yml
+++ b/.github/workflows/ci_11_equistabdatabase.yml
@@ -108,5 +108,10 @@ jobs:
           cd src_latt && make -f Makefile_equistabdatabase && cd ..
           echo "After compilation of equi-stab database code"
 
-          cd CI_tests/EquiStabDatabase && ../../gap.sh < TestEquiStabDatabase.g && cd ../..
+          cd CI_tests/EquiStabDatabase && ../../gap.sh < TestEquiStabDatabase.g
+          if [ ! -f "CI_CONCLUSION" ]; then
+            echo "Error: file not found!" >&2
+            exit 1
+          fi
+          cd ../..
           echo "After Stab/Equi tests"
