Another bunch of changes related to CI.

diff --git a/.github/workflows/ci_19_indefinite_comp.yml b/.github/workflows/ci_19_indefinite_comp.yml
--- a/.github/workflows/ci_19_indefinite_comp.yml
+++ b/.github/workflows/ci_19_indefinite_comp.yml
@@ -105,5 +105,10 @@ jobs:
           echo "After compilation of indefinite codes"
 
           # Running the test
-          cd CI_tests/IndefiniteComp && ../../gap.sh < AllTests.g && cd ../..
+          cd CI_tests/IndefiniteComp && ../../gap.sh < AllTests.g
+          if [ ! -f "CI_CONCLUSION" ]; then
+            echo "Error: file not found!" >&2
+            exit 1
+          fi
+          cd ../..
           echo "After the tests"
diff --git a/.github/workflows/ci_23_integral_points.yml b/.github/workflows/ci_23_integral_points.yml
--- a/.github/workflows/ci_23_integral_points.yml
+++ b/.github/workflows/ci_23_integral_points.yml
@@ -106,4 +106,10 @@ jobs:
           echo "After compilation of relevant code"
 
           # Running the test
-          cd CI_tests/IntegralPoints && ../../gap.sh < TestIntegralPoint.g && cd ../..
+          cd CI_tests/IntegralPoints && ../../gap.sh < TestIntegralPoint.g
+          if [ ! -f "CI_CONCLUSION" ]; then
+            echo "The gap test code has not created the wanted file" >&2
+            exit 1
+          fi
+          cd ../..
+          echo "The integral points computation has failed"
